# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genumer < Formula
  desc "A commandline tool for generating enums in go"
  homepage "https://github.com/kralle333/genumer"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kralle333/genumer/releases/download/v0.1.0/genumer_Darwin_arm64.tar.gz"
      sha256 "8b53a036d7318d381c3a78201dba67c1849a3f02c962262c631b680babbad282"

      def install
        bin.install "genumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kralle333/genumer/releases/download/v0.1.0/genumer_Darwin_x86_64.tar.gz"
      sha256 "2feb4d660b38338b94e93b199e2d2c7dc1619550202be72e8b9673b31cedc580"

      def install
        bin.install "genumer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kralle333/genumer/releases/download/v0.1.0/genumer_Linux_arm64.tar.gz"
      sha256 "586bd087f9bc30e96fe10b85abc6e2bb1e93cb55196d94d138b6e65132eb8f88"

      def install
        bin.install "genumer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kralle333/genumer/releases/download/v0.1.0/genumer_Linux_x86_64.tar.gz"
      sha256 "ab091f6246da05522c7b019307ef25c67b811881ac8193a13ccc52e9fc62b63b"

      def install
        bin.install "genumer"
      end
    end
  end
end
